name: '📦 CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Validate lockfile
        run: npm run lint:lockfile

      - name: Run ESLint
        run: npm run lint:eslint

      - name: Run Prettier
        run: npm run format:check

      - name: Detect unused files with Knip
        run: npm run knip

      - name: Run markdownlint-cli2
        run: npm run lint:docs

      - name: Build extension
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Upload coverage report
        if: success() && hashFiles('coverage/lcov.info') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info

      - name: Package extension
        run: npm run package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-extension
          path: '*.vsix'

      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0.1.10
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: 'You are a helpful assistant.'
